In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

df = pd.read_csv("Global_Superstore.csv")

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,40098,CA-2014-AB10015140-41954,11/11/2014,11/13/2014,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,TEC-PH-5816,Technology,Phones,Samsung Convoy 3,221.98,2,0.0,62.15,40.77,High
1,26341,IN-2014-JR162107-41675,2/5/2014,2/7/2014,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,FUR-CH-5379,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.40,9,0.1,-288.77,923.63,Critical
2,25330,IN-2014-CR127307-41929,10/17/2014,10/18/2014,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,TEC-PH-5356,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.17,9,0.1,919.97,915.49,Medium
3,13524,ES-2014-KM1637548-41667,1/28/2014,1/30/2014,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,TEC-PH-5267,Technology,Phones,"Motorola Smart Phone, Cordless",2892.51,5,0.1,-96.54,910.16,Medium
4,47221,SG-2014-RH9495111-41948,11/5/2014,11/6/2014,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,TEC-CO-6011,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.96,8,0.0,311.52,903.04,Critical

In [3]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          1000 non-null   int64
 1   Order ID        1000 non-null   object
 2   Order Date      1000 non-null   object
 3   Ship Date       1000 non-null   object
 4   Ship Mode       1000 non-null   object
 5   Customer ID     1000 non-null   object
 6   Customer Name   1000 non-null   object
 7   Segment         1000 non-null   object
 8   Postal Code     194 non-null    float64
 9   City            1000 non-null   object
 10  State           1000 non-null   object
 11  Country         1000 non-null   object
 12  Region          1000 non-null   object
 13  Market          1000 non-null   object
 14  Product ID      1000 non-null   object
 15  Category        1000 non-null   object
 16  Sub-Category    1000 non-null   object
 17  Product Name    1000 non-null   object
 18  Sales           1000 non-null   float64
 19  Quantity        1000 non-null   int64
 20  Discount        1000 non-null   float64
 21  Profit          1000 non-null   float64
 22  Shipping Cost   1000 non-null   float64
 23  Order Priority  1000 non-null   object
dtypes: float64(5), int64(2), object(17)
memory usage: 187.6+ KB

Row ID              0
Order ID            0
Order Date          0
Ship Date           0
Ship Mode           0
Customer ID         0
Customer Name       0
Segment             0
Postal Code       806
City                0
State               0
Country             0
Region              0
Market              0
Product ID          0
Category            0
Sub-Category        0
Product Name        0
Sales               0
Quantity            0
Discount            0
Profit              0
Shipping Cost       0
Order Priority      0
dtype: int64

In [4]:
df = df.dropna()

In [5]:
df.fillna(0, inplace=True)

In [6]:
df.fillna("Unknown", inplace=True)

In [7]:
df = df.drop_duplicates()

In [8]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 194 entries, 0 to 996
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          194 non-null    int64
 1   Order ID        194 non-null    object
 2   Order Date      194 non-null    datetime64[ns]
 3   Ship Date       194 non-null    datetime64[ns]
 4   Ship Mode       194 non-null    object
 5   Customer ID     194 non-null    object
 6   Customer Name   194 non-null    object
 7   Segment         194 non-null    object
 8   Postal Code     194 non-null    float64
 9   City            194 non-null    object
 10  State           194 non-null    object
 11  Country         194 non-null    object
 12  Region          194 non-null    object
 13  Market          194 non-null    object
 14  Product ID      194 non-null    object
 15  Category        194 non-null    object
 16  Sub-Category    194 non-null    object
 17  Product Name    194 non-null    object
 18  Sales           194 non-null    float64
 19  Quantity        194 non-null    int64
 20  Discount        194 non-null    float64
 21  Profit          194 non-null    float64
 22  Shipping Cost   194 non-null    float64
 23  Order Priority  194 non-null    object
dtypes: datetime64[ns](2), float64(5), int64(2), object(15)
memory usage: 37.9+ KB

In [10]:
df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()

In [11]:
df.to_csv("cleaned_superstore.csv", index=False)